---
- hosts: groups
  become: no
  gather_facts: no
  tasks:
    - name: check whether agent process running
      shell: ps -ef|grep ultraagent|grep {{ansible_ssh_user}}|grep -v grep|wc -l
      register: result
    - name: kill running agent process
      shell: ps -ef|grep ultraagent|grep {{ansible_ssh_user}}|grep -v grep|awk '{print $2}'|xargs kill -9
      when: result.stdout|int>0
    - name: rollback dirs
      file:
        path: '{{instpath}}'
        state: absent
